"""
Main FastAPI Backend for Job Search Agent
Includes a chat endpoint that interacts with the LangGraph agent
and implicitly manages the background APScheduler in the same process.
"""

from contextlib import asynccontextmanager
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

# Load environment before anything else
from dotenv import load_dotenv
load_dotenv()

from agents.job_search_agent import create_job_search_agent
from tools.scheduler_tool import scheduler

@asynccontextmanager
async def lifespan(app: FastAPI):
    # Ensure scheduler is running when the app starts
    if not scheduler.running:
        scheduler.start()
    print("🚀 FastAPI Server and APScheduler Started!")
    yield
    # Safely shutdown the scheduler when the app stops
    print("🛑 Shutting down APScheduler...")
    if scheduler.running:
        scheduler.shutdown(wait=False)

app = FastAPI(title="AI Job Search Agent API", lifespan=lifespan)

# Configure CORS so any frontend (React/Next.js) can connect
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the LangGraph agent
agent = create_job_search_agent()

class ChatRequest(BaseModel):
    message: str
    thread_id: str = "default_user_session"

class ChatResponse(BaseModel):
    response: str

@app.post("/chat", response_model=ChatResponse)
async def chat_endpoint(req: ChatRequest):
    """
    Endpoint for the frontend chatbot to communicate with the LangGraph agent.
    """
    config = {"configurable": {"thread_id": req.thread_id}}
    
    # Let the agent handle the request
    result = agent.invoke(
        {"messages": [{"role": "user", "content": req.message}]},
        config=config
    )
    
    messages = result.get("messages", [])
    if messages:
        # Extract the AI's latest message content
        last_msg = messages[-1].content
        return {"response": last_msg}
    
    return {"response": "Error: No response generated by the agent."}

@app.get("/health")
async def health_check():
    """Simple check to see if the server and scheduler are running."""
    return {
        "status": "online",
        "scheduler_running": scheduler.running,
        "active_jobs": len(scheduler.get_jobs())
    }

if __name__ == "__main__":
    uvicorn.run("app:app", host="0.0.0.0", port=8000, reload=True)
